"""empty message

Revision ID: 0711c6ee7e84
Revises: b134c6bd49b5
Create Date: 2019-07-31 03:46:10.078264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0711c6ee7e84'
down_revision = 'b134c6bd49b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation=u'utf8mb4_general_ci', length=255), nullable=False))
    # ### end Alembic commands ###
