"""empty message

Revision ID: 254de1b236b2
Revises: 0711c6ee7e84
Create Date: 2019-07-31 03:48:13.834440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254de1b236b2'
down_revision = '0711c6ee7e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
